### ISSUE TITLE
Getting Error during implementation

### ISSUE THREAD

**Issue by himanshutank2179** [lafras-h/JavaPrintooth#1]
i'm using 
implementation files('libs/lambdaj-2.4-with-dependencies.jar')
implementation ('com.github.mazenrashed:Printooth:1.2.1')

So i'm gettig **Error: Program type already present: org.objenesis.ObjenesisBase** this Error.

to fix this issue i tried below and it's successfully compiled
implementation ('com.github.mazenrashed:Printooth:1.2.1'){
exclude group: 'org.objenesis'
}

But when i'm trying to use **Printooth.INSTANCE.hasPairedPrinter()** then it's throwing bellow errror

 java.lang.NoClassDefFoundError: Failed resolution of: Lsun/reflect/ReflectionFactory;
        at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.<init>(SunReflectionFactoryInstantiator.java:40)
        at org.objenesis.strategy.StdInstantiatorStrategy.newInstantiatorOf(StdInstantiatorStrategy.java:85)
        at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1323)
        at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1127)
        at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1136)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:562)
        at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:71)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:734)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:712)
        at io.paperdb.DbStoragePlainFile.readContent(DbStoragePlainFile.java:307)
        at io.paperdb.DbStoragePlainFile.readTableFile(DbStoragePlainFile.java:285)
        at io.paperdb.DbStoragePlainFile.select(DbStoragePlainFile.java:158)
        at io.paperdb.Book.read(Book.java:73)
        at com.mazenrashed.printooth.data.PairedPrinter$Companion.getPairedPrinter(PairedPrinter.kt:14)
        at com.mazenrashed.printooth.Printooth.hasPairedPrinter(Printooth.kt:58)
        at com.shapemore.btprinterdemo.MainActivity.onCreate(MainActivity.java:42)
        at android.app.Activity.performCreate(Activity.java:6666)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
        at android.os.Handler.dispatchMessage(Handler.java:110)

**Comment by fathullah-7** [comment]
i am gettting this issue while printing 
 getBluetoothService() called with no BluetoothManagerCallback
